name: Go

on:
  release:
    types: [created]

jobs:
  release-linux-amd64:
    name: release linux/amd64
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Go environment
        uses: actions/setup-go@v3.5.0
        with:
          go-version: '1.18'
     
      - name: build
        run: go build ./main.go
        
      - name: GitHub Releases 
        uses: varun-bst/release-action@v1.7
        with:
          token: ${{ secrets.RELEASE_TOKEN }}
          artifacts: "main.exe"
