name: Go

on:
  release:
    types: [created]

jobs:
  release-linux-amd64:
    name: release linux/amd64
    runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         # build and publish in parallel: linux/386, linux/amd64, linux/arm64, windows/386, windows/amd64, darwin/amd64, darwin/arm64
#         goos: [linux, windows, darwin]
#         goarch: [amd64, arm64]
#         exclude:
#           - goarch: arm64
#             goos: windows
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go environment
        uses: actions/setup-go@v3.5.0
        with:
          go-version: '1.18'
     
      - name: build
        run: go build ./main.go
        
      - name: GitHub Releases 
        uses: varun-bst/release-action@v1.7
        with:
          token: ${{ secrets.RELEASE_TOKEN }}
          artifacts: "main.exe"
